"""Build manuscript tables directly from frozen result CSV files.

The script is deliberately read-only with respect to all experiment outputs.
It writes only LaTeX fragments under ``breeze/paper/generated`` and fails if a
required frozen input is absent.  Values in the manuscript are therefore not
hand-transcribed from reports.
"""

from __future__ import annotations

import csv
import os
import tempfile
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "breeze" / "paper" / "generated"
PHASE_A = ROOT / "breeze" / "results" / "phaseA_v2_frozen_2026-07-06" / "breeze" / "results"
CWRU = ROOT / "breeze" / "results" / "cwru_patch_v2_2026-07-07_frozen"
BERKELEY = ROOT / "breeze" / "results" / "milling_berkeley_v2_binary_formal_2026-07-08"
PHYSICS = ROOT / "breeze" / "results" / "ablation_2026-07-14"


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"required frozen input is missing: {path}")
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, raw = tempfile.mkstemp(prefix=path.name, suffix=".tmp", dir=path.parent)
    os.close(fd)
    tmp = Path(raw)
    try:
        tmp.write_text(content)
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def tex(value: str) -> str:
    return value.replace("_", r"\_").replace(">", r"$>$")


def pm(mean: str, std: str) -> str:
    return f"{float(mean):.3f} $\\pm$ {float(std):.3f}"


def q(value: str) -> str:
    number = float(value)
    return "<0.001" if number < 0.001 else f"{number:.3f}"


def build_pu() -> None:
    summary = read_csv(PHASE_A / "phaseA_v2_downstream_summary.csv")
    tests = read_csv(PHASE_A / "phaseA_v2_wilcoxon.csv")
    lookup = {(row["baseline"], int(row["n_real"]), row["metric"]): row for row in summary}
    test_lookup = {(int(row["n_real"]), row["metric"], row["comparison"]): row for row in tests}
    names = {
        "phaseA_v2_llm_k3": "LLM $K=3$",
        "phaseA_v2_rule": "rule",
        "phaseA_v2_random_open_loop": "random",
    }
    lines = [
        "% Generated by breeze/scripts/build_paper_tables.py; do not edit.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{PU Phase-A v2 file-split results (20 seeds; $n_{\rm syn}=150$ per class). Holm $q$ values test LLM $K=3$ superiority within each registered family.}",
        r"\label{tab:pu-phasea}",
        r"\small",
        r"\begin{tabular}{rrccccc}",
        r"\toprule",
        r"$n_{\rm real}$ & metric & LLM $K=3$ & rule & random & $q_{\rm rule}$ & $q_{\rm random}$ \\",
        r"\midrule",
    ]
    for n_real in (5, 10, 25):
        for metric, label in (("acc", "Acc."), ("macro_f1", "Macro-F1")):
            values = [pm(lookup[(method, n_real, metric)]["mean"], lookup[(method, n_real, metric)]["std"]) for method in names]
            rule_test = test_lookup[(n_real, metric, "phaseA_v2_llm_k3>phaseA_v2_rule")]
            random_test = test_lookup[(n_real, metric, "phaseA_v2_llm_k3>phaseA_v2_random_open_loop")]
            lines.append(f"{n_real} & {label} & {values[0]} & {values[1]} & {values[2]} & {q(rule_test['holm_q_in_family'])} & {q(random_test['holm_q_in_family'])} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    atomic_text(OUT / "pu_phasea.tex", "\n".join(lines))


def build_cwru() -> None:
    summary = read_csv(CWRU / "cwru_patch_v2_summary.csv")
    tests = read_csv(CWRU / "cwru_patch_v2_wilcoxon.csv")
    lookup = {(row["split"], row["method"], int(row["n_real"]), row["metric"]): row for row in summary}
    registered = len(tests)
    passed = sum(row["passed_holm"] == "True" for row in tests)
    lines = [
        "% Generated by breeze/scripts/build_paper_tables.py; do not edit.",
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{CWRU within-load0 results (40 seeds). All {passed}/{registered} registered LLM-comparator tests across within and four LOLO folds pass Holm correction; the table gives the within-load0 means.}}",
        r"\label{tab:cwru}",
        r"\small",
        r"\begin{tabular}{rrccc}",
        r"\toprule",
        r"$n_{\rm real}$ & metric & LLM & rule & noise augmentation \\",
        r"\midrule",
    ]
    for n_real in (5, 10, 25):
        for metric, label in (("acc", "Acc."), ("macro_f1", "Macro-F1")):
            values = [pm(lookup[("within_load0", method, n_real, metric)]["mean"], lookup[("within_load0", method, n_real, metric)]["std"]) for method in ("llm", "rule", "noise_aug")]
            lines.append(f"{n_real} & {label} & {values[0]} & {values[1]} & {values[2]} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    atomic_text(OUT / "cwru.tex", "\n".join(lines))


def build_berkeley() -> None:
    summary = read_csv(BERKELEY / "berkeley_v2_binary_formal_summary.csv")
    tests = read_csv(BERKELEY / "berkeley_v2_binary_formal_wilcoxon_holm.csv")
    lookup = {(row["method"], int(row["n_real"])): row for row in summary}
    gate = defaultdict(int)
    for row in tests:
        gate[row["comparison"]] += row["pass"] == "True"
    lines = [
        "% Generated by breeze/scripts/build_paper_tables.py; do not edit.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Berkeley binary milling formal test (40 seeds; $n_{\rm syn}=20$ per class). This is a partial result: all comparisons against noise augmentation and random open-loop pass, whereas LLM versus rule passes only Acc. at $n_{\rm real}=2$ and both metrics at $n_{\rm real}=5$.}",
        r"\label{tab:berkeley}",
        r"\small",
        r"\begin{tabular}{rrcccc}",
        r"\toprule",
        r"$n_{\rm real}$ & metric & LLM & rule & noise aug. & random open-loop \\",
        r"\midrule",
    ]
    for n_real in (2, 5, 10):
        for metric, column in (("Acc.", ("mean_acc", "std_acc")), ("Macro-F1", ("mean_macro_f1", "std_macro_f1"))):
            values = [pm(lookup[(method, n_real)][column[0]], lookup[(method, n_real)][column[1]]) for method in ("llm", "rule", "noise_aug", "random_open_loop")]
            lines.append(f"{n_real} & {metric} & {values[0]} & {values[1]} & {values[2]} & {values[3]} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    atomic_text(OUT / "berkeley.tex", "\n".join(lines))


def build_physics() -> None:
    rows = read_csv(PHYSICS / "physics_frozen_full_v3_pu" / "physics_metrics.csv")
    wanted = ("rms_w1", "psd_w1_mean", "band_energy_relative_error_mean", "nn_diversity")
    by = defaultdict(list)
    for row in rows:
        if row["metric"] in wanted:
            by[(row["pool"], row["metric"])].append(float(row["value"]))
    lines = [
        "% Generated by breeze/scripts/build_paper_tables.py; do not edit.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Class-averaged PU physical diagnostics for fixed 150-window/class pools. Distances and errors are reference-relative diagnostics, not a downstream ranking; diversity has no preferred direction.}",
        r"\label{tab:physics}",
        r"\small",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"pool & RMS W1 & PSD W1 & band-energy error & NN diversity \\",
        r"\midrule",
    ]
    for pool in ("llm", "rule", "random_open_loop", "noise_aug"):
        values = [sum(by[(pool, metric)]) / len(by[(pool, metric)]) for metric in wanted]
        lines.append(f"{tex(pool)} & {values[0]:.3f} & {values[1]:.1f} & {values[2]:.3f} & {values[3]:.2f} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    atomic_text(OUT / "physics.tex", "\n".join(lines))


def main() -> None:
    build_pu()
    build_cwru()
    build_berkeley()
    build_physics()
    print(OUT)


if __name__ == "__main__":
    main()
